// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateInteractionRequest defines model for CreateInteractionRequest.
type CreateInteractionRequest struct {
	// Author Username or display name of the author.
	Author string `json:"author"`

	// Body Markdown/text content of the post or reply.
	Body string `json:"body"`

	// GroupId Board/Group identifier.
	GroupId *string `json:"group_id,omitempty"`

	// ParentId Null for root posts; points to immediate parent for replies.
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`

	// Title Title for root posts; omitted or null for replies.
	Title *string `json:"title,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: post not found
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Interaction defines model for Interaction.
type Interaction struct {
	// Author Example: Alice
	Author string `json:"author"`

	// Body Example: This is the body content.
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`

	// Depth Nesting depth (0 = root post, 1 = direct reply, 2+ = nested).
	Depth int `json:"depth"`

	// GroupId Example: root
	GroupId string `json:"group_id"`

	// Id Time-ordered UUIDv7 identifier.
	Id openapi_types.UUID `json:"id"`

	// ParentId Null for root posts; points to immediate parent interaction.
	ParentId   *openapi_types.UUID `json:"parent_id,omitempty"`
	ReplyCount int                 `json:"reply_count"`

	// RootId Null for root posts; points to the conversation thread root.
	RootId *openapi_types.UUID `json:"root_id,omitempty"`

	// Title Example: Welcome to the Message Board
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Version Version number for optimistic concurrency control.
	//
	// Example: 1
	Version int `json:"version"`
}

// InteractionDetail defines model for InteractionDetail.
type InteractionDetail struct {
	Interaction Interaction   `json:"interaction"`
	Replies     []Interaction `json:"replies"`
}

// InteractionFeedResponse defines model for InteractionFeedResponse.
type InteractionFeedResponse struct {
	Interactions []Interaction `json:"interactions"`

	// NextCursor Cursor to pass as cursor query param for subsequent page.
	NextCursor *time.Time `json:"next_cursor,omitempty"`
}

// UpdateInteractionRequest defines model for UpdateInteractionRequest.
type UpdateInteractionRequest struct {
	// Body Updated markdown/text content.
	Body string `json:"body"`

	// Title Updated title for root posts; null or omitted for replies.
	Title *string `json:"title,omitempty"`

	// Version Current version for optimistic concurrency control.
	Version int `json:"version"`
}

// ListInteractionsParams defines parameters for ListInteractions.
type ListInteractionsParams struct {
	// GroupId Board/Group identifier (defaults to root).
	GroupId *string `form:"group_id,omitempty" json:"group_id,omitempty"`

	// Limit Maximum number of interactions to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor timestamp for scrollback pagination.
	Cursor *time.Time `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateInteractionParams defines parameters for CreateInteraction.
type CreateInteractionParams struct {
	// IdempotencyKey Client-provided idempotency key used to derive a deterministic interaction ID. Retries with the same key return the existing interaction (200 OK) instead of creating a duplicate.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// EventsInteractionsParams defines parameters for EventsInteractions.
type EventsInteractionsParams struct {
	// GroupId Optional board/group filter.
	GroupId *string `form:"group_id,omitempty" json:"group_id,omitempty"`
}

// CreateInteractionJSONRequestBody defines body for CreateInteraction for application/json ContentType.
type CreateInteractionJSONRequestBody = CreateInteractionRequest

// UpdateInteractionJSONRequestBody defines body for UpdateInteraction for application/json ContentType.
type UpdateInteractionJSONRequestBody = UpdateInteractionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /v1/healthz)
	GetHealthz(ctx echo.Context) error
	// ListInteractions List root interactions (Feed)
	// (GET /v1/interactions)
	ListInteractions(ctx echo.Context, params ListInteractionsParams) error
	// CreateInteraction Create an interaction
	// (POST /v1/interactions)
	CreateInteraction(ctx echo.Context, params CreateInteractionParams) error
	// EventsInteractions Stream interactions
	// (GET /v1/interactions/events)
	EventsInteractions(ctx echo.Context, params EventsInteractionsParams) error
	// GetInteraction Get interaction with replies
	// (GET /v1/interactions/{id})
	GetInteraction(ctx echo.Context, id openapi_types.UUID) error
	// UpdateInteraction Edit an interaction
	// (PUT /v1/interactions/{id})
	UpdateInteraction(ctx echo.Context, id openapi_types.UUID) error
	// GetReadyz Readiness probe
	// (GET /v1/readyz)
	GetReadyz(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// ListInteractions converts echo context to params.
func (w *ServerInterfaceWrapper) ListInteractions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInteractionsParams
	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", ctx.QueryParams(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter group_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInteractions(ctx, params)
	return err
}

// CreateInteraction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInteraction(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateInteractionParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Idempotency-Key, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Idempotency-Key: %s", err))
		}

		params.IdempotencyKey = IdempotencyKey
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Idempotency-Key is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInteraction(ctx, params)
	return err
}

// EventsInteractions converts echo context to params.
func (w *ServerInterfaceWrapper) EventsInteractions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params EventsInteractionsParams
	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", ctx.QueryParams(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter group_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EventsInteractions(ctx, params)
	return err
}

// GetInteraction converts echo context to params.
func (w *ServerInterfaceWrapper) GetInteraction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInteraction(ctx, id)
	return err
}

// UpdateInteraction converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateInteraction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateInteraction(ctx, id)
	return err
}

// GetReadyz converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadyz(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/v1/healthz", wrapper.GetHealthz, options.OperationMiddlewares["GetHealthz"]...)
	router.GET(options.BaseURL+"/v1/readyz", wrapper.GetReadyz, options.OperationMiddlewares["GetReadyz"]...)
	router.GET(options.BaseURL+"/v1/interactions", wrapper.ListInteractions, options.OperationMiddlewares["ListInteractions"]...)
	router.POST(options.BaseURL+"/v1/interactions", wrapper.CreateInteraction, options.OperationMiddlewares["CreateInteraction"]...)
	router.GET(options.BaseURL+"/v1/interactions/:id", wrapper.GetInteraction, options.OperationMiddlewares["GetInteraction"]...)
	router.PUT(options.BaseURL+"/v1/interactions/:id", wrapper.UpdateInteraction, options.OperationMiddlewares["UpdateInteraction"]...)
	router.GET(options.BaseURL+"/v1/interactions/events", wrapper.EventsInteractions, options.OperationMiddlewares["EventsInteractions"]...)

}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthResponse

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInteractionsRequestObject struct {
	Params ListInteractionsParams
}

type ListInteractionsResponseObject interface {
	VisitListInteractionsResponse(w http.ResponseWriter) error
}

type ListInteractions200JSONResponse InteractionFeedResponse

func (response ListInteractions200JSONResponse) VisitListInteractionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInteractionRequestObject struct {
	Params CreateInteractionParams
	Body   *CreateInteractionJSONRequestBody
}

type CreateInteractionResponseObject interface {
	VisitCreateInteractionResponse(w http.ResponseWriter) error
}

type CreateInteraction201JSONResponse Interaction

func (response CreateInteraction201JSONResponse) VisitCreateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInteraction400JSONResponse ErrorResponse

func (response CreateInteraction400JSONResponse) VisitCreateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInteraction404JSONResponse ErrorResponse

func (response CreateInteraction404JSONResponse) VisitCreateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EventsInteractionsRequestObject struct {
	Params EventsInteractionsParams
}

type EventsInteractionsResponseObject interface {
	VisitEventsInteractionsResponse(w http.ResponseWriter) error
}

type EventsInteractions200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response EventsInteractions200TexteventStreamResponse) VisitEventsInteractionsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type GetInteractionRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetInteractionResponseObject interface {
	VisitGetInteractionResponse(w http.ResponseWriter) error
}

type GetInteraction200JSONResponse InteractionDetail

func (response GetInteraction200JSONResponse) VisitGetInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInteraction404JSONResponse ErrorResponse

func (response GetInteraction404JSONResponse) VisitGetInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInteractionRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateInteractionJSONRequestBody
}

type UpdateInteractionResponseObject interface {
	VisitUpdateInteractionResponse(w http.ResponseWriter) error
}

type UpdateInteraction200JSONResponse Interaction

func (response UpdateInteraction200JSONResponse) VisitUpdateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInteraction400JSONResponse ErrorResponse

func (response UpdateInteraction400JSONResponse) VisitUpdateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInteraction404JSONResponse ErrorResponse

func (response UpdateInteraction404JSONResponse) VisitUpdateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInteraction409JSONResponse ErrorResponse

func (response UpdateInteraction409JSONResponse) VisitUpdateInteractionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse HealthResponse

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse HealthResponse

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /v1/healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// ListInteractions List root interactions (Feed)
	// (GET /v1/interactions)
	ListInteractions(ctx context.Context, request ListInteractionsRequestObject) (ListInteractionsResponseObject, error)
	// CreateInteraction Create an interaction
	// (POST /v1/interactions)
	CreateInteraction(ctx context.Context, request CreateInteractionRequestObject) (CreateInteractionResponseObject, error)
	// EventsInteractions Stream interactions
	// (GET /v1/interactions/events)
	EventsInteractions(ctx context.Context, request EventsInteractionsRequestObject) (EventsInteractionsResponseObject, error)
	// GetInteraction Get interaction with replies
	// (GET /v1/interactions/{id})
	GetInteraction(ctx context.Context, request GetInteractionRequestObject) (GetInteractionResponseObject, error)
	// UpdateInteraction Edit an interaction
	// (PUT /v1/interactions/{id})
	UpdateInteraction(ctx context.Context, request UpdateInteractionRequestObject) (UpdateInteractionResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /v1/readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx echo.Context) error {
	var request GetHealthzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx.Request().Context(), request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		return validResponse.VisitGetHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInteractions operation middleware
func (sh *strictHandler) ListInteractions(ctx echo.Context, params ListInteractionsParams) error {
	var request ListInteractionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInteractions(ctx.Request().Context(), request.(ListInteractionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInteractions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInteractionsResponseObject); ok {
		return validResponse.VisitListInteractionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateInteraction operation middleware
func (sh *strictHandler) CreateInteraction(ctx echo.Context, params CreateInteractionParams) error {
	var request CreateInteractionRequestObject

	request.Params = params

	var body CreateInteractionJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInteraction(ctx.Request().Context(), request.(CreateInteractionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInteraction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateInteractionResponseObject); ok {
		return validResponse.VisitCreateInteractionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EventsInteractions operation middleware
func (sh *strictHandler) EventsInteractions(ctx echo.Context, params EventsInteractionsParams) error {
	var request EventsInteractionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EventsInteractions(ctx.Request().Context(), request.(EventsInteractionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventsInteractions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EventsInteractionsResponseObject); ok {
		return validResponse.VisitEventsInteractionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInteraction operation middleware
func (sh *strictHandler) GetInteraction(ctx echo.Context, id openapi_types.UUID) error {
	var request GetInteractionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInteraction(ctx.Request().Context(), request.(GetInteractionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInteraction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInteractionResponseObject); ok {
		return validResponse.VisitGetInteractionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateInteraction operation middleware
func (sh *strictHandler) UpdateInteraction(ctx echo.Context, id openapi_types.UUID) error {
	var request UpdateInteractionRequestObject

	request.Id = id

	var body UpdateInteractionJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInteraction(ctx.Request().Context(), request.(UpdateInteractionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInteraction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateInteractionResponseObject); ok {
		return validResponse.VisitUpdateInteractionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(ctx echo.Context) error {
	var request GetReadyzRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx.Request().Context(), request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		return validResponse.VisitGetReadyzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
