// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/mock_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	database "github.com/rlsvr/kozlony/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockInteractionCache is a mock of InteractionCache interface.
type MockInteractionCache struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionCacheMockRecorder
	isgomock struct{}
}

// MockInteractionCacheMockRecorder is the mock recorder for MockInteractionCache.
type MockInteractionCacheMockRecorder struct {
	mock *MockInteractionCache
}

// NewMockInteractionCache creates a new mock instance.
func NewMockInteractionCache(ctrl *gomock.Controller) *MockInteractionCache {
	mock := &MockInteractionCache{ctrl: ctrl}
	mock.recorder = &MockInteractionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionCache) EXPECT() *MockInteractionCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockInteractionCache) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInteractionCacheMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInteractionCache)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockInteractionCache) Get(ctx context.Context, id uuid.UUID) (*database.Interaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*database.Interaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInteractionCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInteractionCache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockInteractionCache) Set(ctx context.Context, item *database.Interaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInteractionCacheMockRecorder) Set(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInteractionCache)(nil).Set), ctx, item)
}
