// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package commands

// Command payload to create a new interaction.
type CreateInteractionCommand struct {
	// Author name.
	Author string `json:"author"`

	// Body content.
	Body string `json:"body"`

	// Board or group identifier.
	GroupID string `json:"group_id,omitempty"`

	// Parent interaction UUID for replies.
	ParentID CreateInteractionCommandParentID `json:"parent_id,omitempty"`

	// Title for root posts.
	Title CreateInteractionCommandTitle `json:"title,omitempty"`
}

// Parent interaction UUID for replies.
type CreateInteractionCommandParentID *string

// Title for root posts.
type CreateInteractionCommandTitle *string
