// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package events

import "time"

// Event emitted when a post or reply is created.
type InteractionCreatedEvent struct {
	// Author display name.
	Author string `json:"author"`

	// Markdown content.
	Body string `json:"body"`

	// Timestamp when created.
	CreatedAt time.Time `json:"created_at"`

	// Tree depth (0 for root).
	Depth int `json:"depth"`

	// Board or group identifier.
	GroupID string `json:"group_id"`

	// UUIDv7 identifier.
	ID string `json:"id"`

	// Pointer to the immediate parent interaction.
	ParentID InteractionCreatedEventParentID `json:"parent_id,omitempty"`

	// Direct replies count.
	ReplyCount int `json:"reply_count"`

	// Pointer to the root post of the conversation.
	RootID InteractionCreatedEventRootID `json:"root_id,omitempty"`

	// Post title, null for replies.
	Title InteractionCreatedEventTitle `json:"title,omitempty"`
}

// Pointer to the immediate parent interaction.
type InteractionCreatedEventParentID *string

// Pointer to the root post of the conversation.
type InteractionCreatedEventRootID *string

// Post title, null for replies.
type InteractionCreatedEventTitle *string
