// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package events

import "time"

// Event emitted when an interaction is edited.
type InteractionEditedEvent struct {
	// Updated body content.
	Body string `json:"body"`

	// Board or group identifier.
	GroupID string `json:"group_id"`

	// Interaction UUID.
	ID string `json:"id"`

	// Updated title (for root posts).
	Title InteractionEditedEventTitle `json:"title,omitempty"`

	// Timestamp when edited.
	UpdatedAt time.Time `json:"updated_at"`

	// Incremented interaction version number.
	Version int `json:"version"`
}

// Updated title (for root posts).
type InteractionEditedEventTitle *string
