// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	events "github.com/rlsvr/kozlony/internal/messaging/events"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPublisher) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPublisherMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPublisher)(nil).Ping), ctx)
}

// PublishInteractionCreated mocks base method.
func (m *MockPublisher) PublishInteractionCreated(ctx context.Context, evt *events.InteractionCreatedEvent) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInteractionCreated", ctx, evt)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishInteractionCreated indicates an expected call of PublishInteractionCreated.
func (mr *MockPublisherMockRecorder) PublishInteractionCreated(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInteractionCreated", reflect.TypeOf((*MockPublisher)(nil).PublishInteractionCreated), ctx, evt)
}

// PublishInteractionEdited mocks base method.
func (m *MockPublisher) PublishInteractionEdited(ctx context.Context, evt *events.InteractionEditedEvent) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInteractionEdited", ctx, evt)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishInteractionEdited indicates an expected call of PublishInteractionEdited.
func (mr *MockPublisherMockRecorder) PublishInteractionEdited(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInteractionEdited", reflect.TypeOf((*MockPublisher)(nil).PublishInteractionEdited), ctx, evt)
}

// SubscribeEvents mocks base method.
func (m *MockPublisher) SubscribeEvents(ctx context.Context, groupID *string) (<-chan []byte, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeEvents", ctx, groupID)
	ret0, _ := ret[0].(<-chan []byte)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockPublisherMockRecorder) SubscribeEvents(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockPublisher)(nil).SubscribeEvents), ctx, groupID)
}
