// Code generated by MockGen. DO NOT EDIT.
// Source: drainer.go
//
// Generated by this command:
//
//	mockgen -source=drainer.go -destination=mocks/mock_drainer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockPullConsumer is a mock of PullConsumer interface.
type MockPullConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockPullConsumerMockRecorder
	isgomock struct{}
}

// MockPullConsumerMockRecorder is the mock recorder for MockPullConsumer.
type MockPullConsumerMockRecorder struct {
	mock *MockPullConsumer
}

// NewMockPullConsumer creates a new mock instance.
func NewMockPullConsumer(ctrl *gomock.Controller) *MockPullConsumer {
	mock := &MockPullConsumer{ctrl: ctrl}
	mock.recorder = &MockPullConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullConsumer) EXPECT() *MockPullConsumerMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockPullConsumer) Fetch(batch int, opts ...jetstream.FetchOpt) (jetstream.MessageBatch, error) {
	m.ctrl.T.Helper()
	varargs := []any{batch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(jetstream.MessageBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockPullConsumerMockRecorder) Fetch(batch any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{batch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockPullConsumer)(nil).Fetch), varargs...)
}
